name: hello with input

on:
  workflow_dispatch:
    inputs:
      my_hello_input:
        description: 'Hello input'
        required: true
        default: 'This is a default hello input'

jobs:
  hello_job:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Hello, ${{ github.event.inputs.my_hello_input }}" >> $GITHUB_STEP_SUMMARY
